version: "3"
services:
  api:
    build: .
    image: propelize-web-api
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: propelize
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
volumes:
  mysql-data:
