openapi: 3.0.0
info:
  title: API Propelize
  version: 1.0.0
  description: |
    API de gestion des utilisateurs et des véhicules pour le système de location Propelize.

servers:
  - url: http://localhost:3000/api
    description: Serveur de développement

paths:
  /users:
    get:
      tags: [Utilisateurs]
      summary: Récupérer tous les utilisateurs
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserProfile"
        "401":
          description: Non authentifié

  /users/register:
    post:
      tags: [Utilisateurs]
      summary: Enregistrement d'un nouvel utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegister"
      responses:
        "201":
          description: Utilisateur créé avec tokens
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "400":
          description: |
            Erreurs possibles :
            - Email déjà utilisé
            - Données manquantes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/login:
    post:
      tags: [Utilisateurs]
      summary: Connexion utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
      responses:
        "200":
          description: Connexion réussie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "401":
          description: Identifiants invalides
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/refresh-token:
    post:
      tags: [Utilisateurs]
      summary: Rafraîchir le token d'accès
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
              required: [refreshToken]
      responses:
        "200":
          description: Nouveau token généré
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        "401":
          description: Refresh token invalide ou expiré

  /users/{id}:
    put:
      tags: [Utilisateurs]
      summary: Mettre à jour un utilisateur
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/UserId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
      responses:
        "200":
          description: Utilisateur mis à jour
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        "403":
          description: |
            Interdit :
            - Tentative de modification d'un autre utilisateur sans droits admin
        "404":
          description: Utilisateur non trouvé

    delete:
      tags: [Utilisateurs]
      summary: Supprimer un utilisateur
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/UserId"
      responses:
        "204":
          description: Utilisateur supprimé
        "404":
          description: Utilisateur non trouvé
  /vehicles:
    post:
      tags:
        - Véhicules
      summary: Créer un nouveau véhicule
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VehicleInput"
      responses:
        "201":
          description: Véhicule créé avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vehicle"
        "400":
          description: Données invalides
        "401":
          description: Non autorisé

    get:
      tags:
        - Véhicules
      summary: Lister tous les véhicules
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/pageParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: Liste des véhicules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Vehicle"
        "401":
          description: Non autorisé

  /vehicles/{id}:
    get:
      tags:
        - Véhicules
      summary: Obtenir un véhicule par ID
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/idParam"
      responses:
        "200":
          description: Détails du véhicule
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vehicle"
        "404":
          description: Véhicule non trouvé
        "401":
          description: Non autorisé

    put:
      tags:
        - Véhicules
      summary: Mettre à jour un véhicule
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/idParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VehicleUpdate"
      responses:
        "200":
          description: Véhicule mis à jour
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        "404":
          description: Véhicule non trouvé
        "401":
          description: Non autorisé

    delete:
      tags:
        - Véhicules
      summary: Supprimer un véhicule
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/idParam"
      responses:
        "204":
          description: Véhicule supprimé
        "404":
          description: Véhicule non trouvé
        "401":
          description: Non autorisé

  /vehicles/search/{registrationNumber}:
    get:
      tags:
        - Véhicules
      summary: Rechercher un véhicule par immatriculation
      security:
        - bearerAuth: []
      parameters:
        - name: registrationNumber
          in: path
          required: true
          schema:
            type: string
          example: "ABC123"
          description: Numéro d'immatriculation
      responses:
        "200":
          description: Véhicule trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vehicle"
        "404":
          description: Véhicule non trouvé
        "401":
          description: Non autorisé

  /vehicles/price/{maxPrice}:
    get:
      tags:
        - Véhicules
      summary: Filtrer les véhicules par prix maximum
      security:
        - bearerAuth: []
      parameters:
        - name: maxPrice
          in: path
          required: true
          schema:
            type: number
            format: float
          example: 50.00
          description: Prix maximum de location
      responses:
        "200":
          description: Liste des véhicules filtrés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Vehicle"
        "401":
          description: Non autorisé

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    UserId:
      name: id
      in: path
      required: true
      schema:
        type: integer
        example: 1
      description: ID utilisateur
    idParam:
      name: id
      in: path
      required: true
      schema:
        type: integer
      description: ID du véhicule
    pageParam:
      name: page
      in: query
      schema:
        type: integer
        default: 1
    limitParam:
      name: limit
      in: query
      schema:
        type: integer
        default: 10

  schemas:
    UserRegister:
      type: object
      required: [name, password]
      properties:
        name:
          type: string
          example: "John Doe"
          minLength: 3
        password:
          type: string
          format: password
          example: "securePassword123"
          minLength: 6

    UserLogin:
      type: object
      required: [name, password]
      properties:
        name:
          type: string
          example: "Admin"
        password:
          type: string
          example: "admin123"

    UserUpdate:
      type: object
      properties:
        name:
          type: string
          example: "Nouveau Nom"
        password:
          type: string
          format: password

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: Token valable 15 minutes
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        refreshToken:
          type: string
          description: Token valable 7 jours
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        id:
          type: integer
        name:
          type: string

    UserProfile:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Error:
      type: object
      properties:
        error:
          type: string
          example: "Email already exists"
        details:
          type: string
          example: "Validation error"

    Vehicle:
      type: object
      properties:
        id:
          type: integer
          example: 1
        registrationNumber:
          type: string
          example: "ABC123"
        make:
          type: string
          example: "Toyota"
        model:
          type: string
          example: "Camry"
        year:
          type: integer
          example: 2022
        rentalPrice:
          type: number
          format: float
          example: 45.50
        createdAt:
          type: string
          format: date-time

    VehicleInput:
      type: object
      required:
        - registrationNumber
        - make
        - model
        - year
        - rentalPrice
      properties:
        registrationNumber:
          type: string
        make:
          type: string
        model:
          type: string
        year:
          type: integer
        rentalPrice:
          type: number
          format: float

    VehicleUpdate:
      type: object
      properties:
        registrationNumber:
          type: string
        make:
          type: string
        model:
          type: string
        year:
          type: integer
        rentalPrice:
          type: number
          format: float
